services:
  website:
    build: ./website
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    depends_on:
      - server
    profiles: ["web"]

  mobile:
    build: ./mobile
    ports:
      - 3001:3001
    environment:
      EXPO_PUBLIC_SERVER_URL: ${EXPO_PUBLIC_SERVER_URL}
    depends_on:
      - server
    profiles: ["mobile"]

  server:
    build: ./server
    ports:
      - 3002:3002
    environment:
      DB_NAME: motivation_scale_data
      DB_CONNECTION: mongodb://db:27017
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
