services:
  website:
    build: ./website
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    depends_on:
      - server
    profiles: ["web"]

  mobile:
    build: ./mobile
    ports:
      - 127.0.0.1:3001:3001
    environment:
      EXPO_PUBLIC_SERVER_URL: ${EXPO_PUBLIC_SERVER_URL}
    depends_on:
      - server
    profiles: ["mobile"]

  server:
    build: ./server
    ports:
      - 127.0.0.1:3002:3002
    environment:
      DB_NAME: motivation_scale_data
      DB_CONNECTION: mongodb://db:27017
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - db_data:/data/db

volumes:
  db_data:
