services:
  server:
    build: ./server
    ports:
      - 3001:3001
    env_file: 
    - ${ENV_FILE:-./.env.local} # use .env.local if ENV_FILE variable is not set
    environment:
      DB_NAME: motivation_scale_data
      DB_CONNECTION: mongodb://db:27017
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: db_data
        target: /data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
